export const SHOW_LOADING = "SHOW_LOADING";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCEEDED = "FETCH_USERS_SUCCEEDED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";
