export const SHOW_LOADING = "SHOW_LOADING";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCEEDED = "FETCH_USER_SUCCEEDED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";
